dependencies:
  #- name: nginx-ingress
  #  version: 1.20.1
  #  repository: http://chartmuseum.devops.nuvem.bb.com.br/bb/infra
  - name: k8s-namespaces
    version: 0.1.0
    repository: https://chartmuseum.devops.nuvem.bb.com.br/bb/infra
