---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    cluster.k8s.bb/abbreviation: kad
    cluster.k8s.bb/name: k8s-apps-des
    release.k8s.bb/deploy: argocd
    release.k8s.bb/sigla: psc
  annotations:
    cluster.k8s.bb/api: 'https://kube-api.apps.nuvem.desenv.bb.com.br:6443'
    release.k8s.bb/git: 'https://fontes.intranet.bb.com.br/psc/psc_releases_k8s-apps-des.git'
  name: bb-operacao-admin
  namespace: psc-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bb-operacao-admin
  labels:
    cluster.k8s.bb/abbreviation: kad
    cluster.k8s.bb/name: k8s-apps-des
    release.k8s.bb/deploy: argocd
    release.k8s.bb/sigla: psc
  annotations:
    cluster.k8s.bb/api: 'https://kube-api.apps.nuvem.desenv.bb.com.br:6443'
    release.k8s.bb/git: 'https://fontes.intranet.bb.com.br/psc/psc_releases_k8s-apps-des.git'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: bb-operacao-admin
  namespace: psc-admin