apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: psc-servicos-plataforma
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
value: 1000000
globalDefault: false
description: "Esta priority class deve ser usada em servicos de plataforma apenas."