apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: psc-features-bb-aplic
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
value: 10000
globalDefault: false
description: "Esta priority class deve ser usada no bbaplic quando for habilitada alguma feature pelo dev como NAS ou AVX."