apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: psc-servicos-plataforma
value: 1000000
globalDefault: false
description: "Esta priority class deve ser usada em servicos de plataforma apenas."