service-external-name: #so uns comentarios
  enable: true
  namespace: psc-proxy
  service:
    - name: ldap
      urlExterna: ldp0pb1.bb.com.br
    - name: cachebb
      urlExterna: cache.desenv.bb.com.br